# Generated by Django 3.1 on 2021-06-30 23:19

import ckeditor.fields
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('scientific_name', models.CharField(blank=True, default='', max_length=200)),
                ('benefits', ckeditor.fields.RichTextField(blank=True)),
                ('slug', models.SlugField(max_length=200)),
                ('list_image', stdimage.models.StdImageField(blank=True, upload_to='trees/%Y/%m/%d')),
                ('image1', models.ImageField(blank=True, upload_to='trees/%Y/%m/%d')),
                ('image2', models.ImageField(blank=True, upload_to='trees/%Y/%m/%d')),
                ('image3', models.ImageField(blank=True, upload_to='trees/%Y/%m/%d')),
                ('image4', models.ImageField(blank=True, upload_to='trees/%Y/%m/%d')),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('care', ckeditor.fields.RichTextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('project_summary', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=200)),
                ('image1', models.ImageField(blank=True, upload_to='past_projects/%Y/%m/%d')),
                ('image2', models.ImageField(blank=True, upload_to='past_projects/%Y/%m/%d')),
                ('image3', models.ImageField(blank=True, upload_to='past_projects/%Y/%m/%d')),
                ('image4', models.ImageField(blank=True, upload_to='past_projects/%Y/%m/%d')),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('client_name', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
