# Generated by Django 3.1 on 2021-06-30 21:02

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='list_image',
            field=stdimage.models.StdImageField(blank=True, upload_to='trees/%Y/%m/%d'),
        ),
    ]
