# Generated by Django 3.1 on 2021-06-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='image1',
            field=models.ImageField(blank=True, upload_to='past_projects/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='project',
            name='image2',
            field=models.ImageField(blank=True, upload_to='past_projects/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='project',
            name='image3',
            field=models.ImageField(blank=True, upload_to='past_projects/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='project',
            name='image4',
            field=models.ImageField(blank=True, upload_to='past_projects/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='tree',
            name='image1',
            field=models.ImageField(blank=True, upload_to='trees/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='tree',
            name='image2',
            field=models.ImageField(blank=True, upload_to='trees/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='tree',
            name='image3',
            field=models.ImageField(blank=True, upload_to='trees/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='tree',
            name='image4',
            field=models.ImageField(blank=True, upload_to='trees/%Y/%m/%d'),
        ),
    ]
